[pangeo]
    [pangeo.request]
        url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
        #variable_id = ['tas', 'pr', 'zg']      # Atmosphere (monthly)
        variable_id = ['zg']                    # Atmosphere (monthly)
        #variable_id = ['pr']                    # Atmosphere (monthly)
        #variable_id = ['tos']                  # Ocean (monthly)
        table_id = ['Amon']                     # Atmosphere (monthly)
        #table_id = ['Omon']                    # Ocean (monthly)
        experiment_id = ['historical'] #['historical', 'ssp245', 'ssp370', 'ssp585']
        member_id = ['r1i1p1f1']
        grid_label = ['gr']
        require_all_on=['source_id', 'experiment_id', 'member_id', 'variable_id', 'grid_label']
    [pangeo.ranges]
        #historical = ['1850-01', '2014-12']
        historical = ['1979-01-01', '2014-12-31']
        #projection = ['2015-01-16', '2100-12-16']
    [pangeo.calendar]
        calendar = 'noleap'